#!/usr/bin/env python3
"""
build_real_game.py - HTML Game Builder with Real Lynx Assets

This script builds a complete, standalone HTML5 game file by combining:
  1. extracted_assets.js - Base64-encoded assets extracted from real Lynx screenshots
  2. real_logic.js - Game logic that uses the extracted assets

The output is a single HTML file (Gauntlet_Lynx_Real.html) that can be opened
directly in any modern web browser without a server.

The HTML includes:
  - Responsive viewport settings for mobile
  - Pixelated rendering to preserve retro aesthetic
  - 4x scaled Lynx resolution (102x160 -> 408x640)
  - Dark theme with centered game container

Usage:
    python build_real_game.py

Prerequisites:
    - extracted_assets.js (generated by extract_real_assets.py)
    - real_logic.js (game logic file)

Author: JMR
"""

import os


def build():
    """
    Builds the Gauntlet HTML game with real Lynx assets.
    
    Reads the assets and logic JavaScript files, embeds them into an HTML
    template, and writes the combined output to Gauntlet_Lynx_Real.html.
    
    Returns:
        None. Prints status message on completion or error.
    """
    assets_file = 'extracted_assets.js'
    logic_file = 'real_logic.js'
    output_file = 'Gauntlet_Lynx_Real.html'
    
    # Ensure assets file exists
    if not os.path.exists(assets_file):
        print("Assets file not found!")
        return

    with open(assets_file, 'r') as f:
        assets_content = f.read()
        
    with open(logic_file, 'r') as f:
        logic_content = f.read()
        
    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Gauntlet: The Third Encounter (Real Lynx Assets)</title>
    <style>
        body {{
            margin: 0;
            padding: 0;
            background: #111;
            color: #fff;
            font-family: 'Courier New', monospace;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            overflow: hidden;
        }}
        #gameContainer {{
            position: relative;
            width: 408px; /* 102 * 4 */
            height: 640px; /* 160 * 4 */
            box-shadow: 0 0 20px rgba(0,0,0,0.8);
            border: 10px solid #333;
            background: #000;
        }}
        canvas {{
            display: block;
            width: 100%;
            height: 100%;
            image-rendering: pixelated;
        }}
    </style>
</head>
<body>
    <div id="gameContainer">
        <canvas id="gameCanvas" width="408" height="640"></canvas>
    </div>
    <script>
    // ASSETS
    {assets_content}
    
    // LOGIC
    {logic_content}
    </script>
</body>
</html>
"""
    
    with open(output_file, 'w') as f:
        f.write(html_template)
        
    print(f"Built {output_file}")

if __name__ == "__main__":
    build()

