#!/usr/bin/env python3
"""
build_game.py - HTML Game Builder with Generated Assets

This script builds a complete, standalone HTML5 game file by combining:
  1. gauntlet_assets.js - Programmatically generated Lynx-style sprites
  2. game_logic_lynx.js - Core game logic

The output is a single HTML file (Gauntlet_Lynx_Reforged.html) that can be
opened directly in any modern web browser without a server.

The HTML includes:
  - Responsive viewport settings for mobile
  - Pixelated rendering to preserve retro aesthetic  
  - 480x800 game canvas with bezel styling
  - Dark theme with centered game container

Usage:
    python build_game.py

Prerequisites:
    - gauntlet_assets.js (generated by generate_lynx_assets.py)
    - game_logic_lynx.js (game logic file)

Author: JMR
"""

import os


def build():
    """
    Builds the Gauntlet HTML game with generated Lynx-style assets.
    
    Reads the assets and logic JavaScript files, embeds them into an HTML
    template, and writes the combined output to Gauntlet_Lynx_Reforged.html.
    
    Returns:
        None. Prints status message on completion.
    """
    assets_file = 'gauntlet_assets.js'
    logic_file = 'game_logic_lynx.js'
    output_file = 'Gauntlet_Lynx_Reforged.html'
    
    with open(assets_file, 'r') as f:
        assets_content = f.read()
        
    with open(logic_file, 'r') as f:
        logic_content = f.read()
        
    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Gauntlet: The Third Encounter (Lynx Reforged)</title>
    <style>
        body {{
            margin: 0;
            padding: 0;
            background: #000;
            color: #fff;
            font-family: 'Courier New', monospace;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            overflow: hidden;
        }}
        #gameContainer {{
            position: relative;
            width: 480px;
            height: 800px;
            box-shadow: 0 0 20px rgba(0,0,0,0.5);
            border: 8px solid #444; /* Bezel */
            background: #222;
        }}
        canvas {{
            display: block;
            width: 100%;
            height: 100%;
            image-rendering: pixelated;
        }}
    </style>
</head>
<body>
    <div id="gameContainer">
        <canvas id="gameCanvas" width="480" height="800"></canvas>
    </div>
    <script>
    // ASSETS
    {assets_content}
    
    // LOGIC
    {logic_content}
    </script>
</body>
</html>
"""
    
    with open(output_file, 'w') as f:
        f.write(html_template)
        
    print(f"Built {output_file}")

if __name__ == "__main__":
    build()
